// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trifork_project.Data;

#nullable disable

namespace Triforkproject.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Trifork_project.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Barcode = "123443211245",
                            Brand = "Marabou",
                            Category = "Chocolate"
                        },
                        new
                        {
                            PostId = 2,
                            Barcode = "1234567890123",
                            Brand = "Haribo",
                            Category = "Candy"
                        },
                        new
                        {
                            PostId = 3,
                            Barcode = "8901231234567",
                            Brand = "Schulstad",
                            Category = "Bread"
                        },
                        new
                        {
                            PostId = 4,
                            Barcode = "1234568977972",
                            Brand = "Ben & Jerry's",
                            Category = "Icecream"
                        },
                        new
                        {
                            PostId = 5,
                            Barcode = "4388893289121",
                            Brand = "Head & Shoulders",
                            Category = "Shampoo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
